### ISSUE TITLE
The rest service returns a failure

### ISSUE THREAD

**Issue by davsclaus** [fabric8-quickstarts/infinispan-server#81]
When accessing infinispan over rest it fails.

**Comment by oscerd** [comment]
I guess this is because Infinispan doesn't expose an health check endpoint.

**Comment by oscerd** [comment]
or at least not in that version

**Comment by davsclaus** [comment]
Oh I dont think its that, but not sure what its supposed to return you just get a JAX-RS error from resteasy.

And we dont have a client app that uses this so this QS has little value.

**Comment by oscerd** [comment]
We have:

https://github.com/fabric8-quickstarts/infinispan-client

**Comment by oscerd** [comment]
I worked on the two quickstarts an year ago.

**Comment by oscerd** [comment]
I'll try to understand the problem with rest service.

**Comment by davsclaus** [comment]
Ah thanks there was a client - how could i miss that. Then it works from Camel using the hotrod protocol over 11222 port.
